### ISSUE TITLE
Does not seem to work in a Windows environment

### ISSUE THREAD

**Issue by ScribbleGhost** [aerobounce/trim.lua#5] opened 2021-01-01 16:36 UTC
I have been trying all day to get this to work in Windows with [mpv](https://mpv.io/installation/). ffmpeg is [added to PATH](https://scribbleghost.net/2020/07/05/add-environment-variables-in-windows-10/). The trim.lua script is added to `C:\Users\username\AppData\Roaming\mpv\scripts\`. I am able to set the start and end time with the hotkeys as described in the readme, but once I close mpv with the Q key nothing really happens.

I tried to edit `local args` to match the location of my ffmpeg and ffprobe directory. So now it says `"F:/portable/ffmpeg/bin",`. Doesn't seem to help.

Any suggestions?

**Comment by aerobounce** [comment] 2021-01-04 09:16
Take a look at #3, and additionally, I suggest launching mpv with verbose logging to determine what the exact problem is.

**Comment by aerobounce** [comment] 2021-01-14 10:14
Please provide further information to resolve the issue. Closing for now.

**Comment by iiiGerardoiii** [comment] 2021-01-31 12:54
Hello, I'm the guy who opened and closed issue #4.

I'm trying your new updated script but it seems that rewriting the paths doesn't solve the issue on this new version, at least on Winblows 10.

I changed line 12 and 13 to:
`local ffmpeg_bin = "C:/Users/GerardosPC/mpv-x86_64-20190707-git-c379950/ffmpeg.exe"`
`local ffprobe_bin = "C:/Users/GerardosPC/mpv-x86_64-20190707-git-c379950/ffprobe.exe"`

and here's the log of the error I get:
https://pastebin.com/ve7wqfkp

for comparison, here's the log of a successful trimming (using your [old script](https://pastebin.com/hM0RZGad)):
https://pastebin.com/yrd1tu53

Hope this helps.

**Comment by aerobounce** [comment] 2021-01-31 14:04
Could you try delete lines
https://github.com/aerobounce/trim.lua/blob/dae8716323bae1bc972b2632f045d518caacf390/trim.lua#L286-L287
and see if works?

**Comment by iiiGerardoiii** [comment] 2021-01-31 22:13
> 
> Could you try delete lines 286-287
> 
ah, same error https://pastebin.com/9Xb9LArW

**Comment by aerobounce** [comment] 2021-02-01 07:23
Ah... seems to be a regression, I'll fix it. Thanks for the test.

**Comment by aerobounce** [comment] 2021-02-03 05:50
Okay! I've created and pushed develop branch.
Could you try again with the version?
https://github.com/aerobounce/trim.lua/blob/in-develop/trim.lua

The line you need to change is (ffprobe dependency is removed, you only need ffmpeg now):
https://github.com/aerobounce/trim.lua/blob/12cc004eed36b44bfef82ad3a01c3600a5dda002/trim.lua#L18

_OR_

If `ffmpeg.exe` is stand-alone executable file and if you don't mind copying it to the script directory, I'm assuming you don't even need to make any change to the script.

**Comment by iiiGerardoiii** [comment] 2021-02-03 09:51
It works! Thanks a lot buddy

**Comment by aerobounce** [comment] 2021-02-03 11:10
Cool. For the record, could I ask how you did specify ffmpeg.exe?

1. Did you write full-path to ffmpeg just like before?
2. Or did you copy ffmpeg.exe to script directory?

**Comment by iiiGerardoiii** [comment] 2021-02-03 16:26
Yeah I typed the full-path `ffmpeg_bin = "C:/Users/GerardosPC/mpv-x86_64-20190707-git-c379950/ffmpeg.exe"`

**Comment by aerobounce** [comment] 2021-02-03 18:03
Right, got it. Thanks again for testing.

Closing issue now.

**Closed by aerobounce** 2021-02-03 18:03 UTC
Labels: enhancement
